version: '3.8'

services:
  backend:
    build: .
    container_name: Ayana-Golang-Local
    image: ayana-golang-local:latest
    restart: always
    ports:
      - "8080:8080"
    environment:
      - CLIENT_ORIGIN=https://ayanagroup99.com
    networks:
      - ayana_network

networks:
  ayana_network:
    driver: bridge
